services:
  wallet-tests:
    build:
      context: .
      dockerfile: Dockerfile-tests
    ports:
      - "8002:8001"
    depends_on:
      test-db:
        condition: service_healthy
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_HOST: test-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
    volumes:
      - ./:/app
    networks:
      - wallets-db
    container_name: "wallet-tests"
    entrypoint: ["./app/entrypoint.sh"]

  test-db:
    image: postgres:16.1
    container_name: "test-db"
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_HOST: test-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
    ports:
      - '5433:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wallets-db

networks:
    wallets-db:
      driver: bridge
      name: wallets-db