services:
  wallet:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - wallets
    container_name: "wallets"
  postgres:
    image: postgres:16.1
    container_name: "postgres"
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wallets

networks:
    wallets:
      driver: bridge
      name: wallets